# Generated by Django 3.0.4 on 2020-06-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=13, null=True),
        ),
    ]
